### PR TITLE
General cleanup and fixing tests

### PR DESCRIPTION
**Pull request by vraravam**
The intent of these changes is for the next person who hits upon this codebase (as a reference implementation of `ex_admin`) - they should be able to checkout the code, run `mix deps.get` and `npm install` and `mix ecto.reset` and get the app running with minimal effort.

### CODE REVIEW

**Comment by smpallen99** [comment]
Thanks for the contribution!

**Comment by vraravam** [comment]
You are welcome!
I am still in the process of writing more tests - have put in TODOs in various places. Hope that is fine with you.

I'm also converting the codebase to use `ex_machina` and `ex_spec` - though they might be orthogonal to your intent to showcase `ex_admin` - I felt that this repo can also be a showcase for good elixir/phoenix code with some of these standards incorporated. Thus could act as a jumping board for others to adopt this tech. wdyt?

**Comment by smpallen99** [comment]
Please no ex_spec. Just plain ExUnit.

**Comment by vraravam** [comment]
@smpallen99 : This is the one I was referring to: https://github.com/drewolson/ex_spec

It only _aids_ in organizing the test within `describe/context` blocks. For eg, it allows me to specify that validations are being done for a specific field - thus allowing grouping.

**Comment by smpallen99** [comment]
Yes, I'm familiar with the package. I've used different test packages in the past in my Elixir projects and have rewritten them all to remove. All my projects use ExUnit only. ExUnit's describe is sufficient for grouping IMHO. If ExUnit is enough for testing the Elixir language and Phoenix, then I believe its enough for testing my projects :)

**Comment by vraravam** [comment]
Cool - I will try to remove it and commit.

**Pull request merged**
